spring:
  jedis:
    host: 127.0.0.1
    port: 6379
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: service-redis
  application:
    name: service-redis
server:
  port: 5555

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
