spring:
  jedis:
    host: 127.0.0.1
    port: 6379
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: http-client
  application:
    name: http-client
server:
  port: 5556

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
